package com.altoukhov.world.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.util.Objects;

@Entity
@Table(name = "city")
@Getter
@Setter
@NoArgsConstructor
public class City {

    // Primitives are marked as nullable/non-nullable simply to stay consistent with the related table creation DDL query

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "name", length = 35, nullable = false)
    private String name;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "countrycode", referencedColumnName = "code", nullable = false)
    private Country country;

    @Column(name = "district", length = 20, nullable = false)
    private String districtName;

    @Column(name = "population", nullable = false)
    private int populationCount;

    // Generated by JPA Buddy and modified to not use Hibernate's getClass (this may or may not lead to subtle, incorrect behavior)
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || getClass() != obj.getClass())
            return false;

        City otherCity = (City) obj;
        return Objects.equals(id, otherCity.id);
    }

    // Generated by JPA Buddy
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    // Non-generated to provide a simpler impl and avoid performance issues related to foreign key loading (according to JPA Buddy)
    @Override
    public String toString() {
        return name;
    }
}
